### ISSUE TITLE
질문 : 무슨 프로젝트인가요?

### ISSUE THREAD

**Issue by lionleeee** [yeun38/project-numble#1]
어떠한 프로젝트인지 너무 궁금합니다!!

**Comment by yeun38** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 해당 프로젝트에 참여하게 되었습니다^,^
[](https://www.numble.it/deepdive/7b3932dc-9caa-4c77-a2b5-8ba8dabbd136)

**Comment by lionleeee** [comment]
아 왜 이 좋은 프로젝트 혼자 참여해요~~
